from __future__ import annotations

COCKPIT_HTML = r'''<!doctype html>
<html lang="pt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vazao Sovereign Trader</title>
<style>body{margin:0;background:#0b1020;color:#e8eefc;font:14px Arial}.top{padding:18px;background:#111933;border-bottom:1px solid #24304f;position:sticky;top:0}.wrap{padding:16px;display:grid;gap:14px;grid-template-columns:repeat(auto-fit,minmax(280px,1fr))}.card{background:#121a33;border:1px solid #24304f;border-radius:14px;padding:14px}.wide{grid-column:1/-1}.big{font-size:28px;font-weight:bold}.muted{color:#93a4c7;font-size:13px}button,select,input{padding:11px;border-radius:10px;margin:3px;font-weight:bold;box-sizing:border-box}button{border:0;cursor:pointer}.go{background:#36d399}.pause{background:#fbbf24}.stop{background:#fb7185}.blue{background:#93c5fd}.purple{background:#c4b5fd}select,input{width:100%;background:#090d1a;color:#e8eefc;border:1px solid #33415f}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.check{display:flex;justify-content:space-between;border-bottom:1px solid #24304f;padding:7px}.ok{color:#36d399}.bad{color:#fb7185}.warn{color:#fbbf24}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #24304f;text-align:left}pre{white-space:pre-wrap;max-height:250px;overflow:auto}</style></head>
<body><div class="top"><b>Vazao Sovereign Trader — Cockpit</b><div class="muted">Controlo guiado. PAPER por defeito. Sem frases para decorar.</div></div><div class="wrap">
<div class="card wide"><div class="muted">CONTROLO DO BOT</div><input id="token" type="password" placeholder="Token local (VST_LOCAL_TOKEN)"><br><button class="go" onclick="cmd('/start')">▶ LIGAR</button><button class="pause" onclick="cmd('/pause')">Ⅱ PAUSAR</button><button class="go" onclick="cmd('/resume')">▶ RETOMAR</button><button class="stop" onclick="cmd('/stop')">■ PARAR</button><button class="blue" onclick="setMode('PAPER')">PAPER</button><button class="purple" onclick="cmd('/preflight')">✓ PREFLIGHT</button></div>
<div class="card wide"><div class="muted">REAL — SEGURANÇA</div><div class="row"><div><div id="rt" class="big">A verificar…</div><div id="rs" class="muted">---</div></div><div><select id="phrase"><option value="EU ACEITO O RISCO">EU ACEITO O RISCO — confirmação REAL protegido</option></select><button class="blue" onclick="arm()">🔐 AUTORIZAR REAL (5 MIN)</button><button class="stop" onclick="cmd('/real/disarm')">🔒 BLOQUEAR REAL</button><div id="guard" class="muted">---</div></div></div><div id="checks"></div><div class="muted">A confirmação fica pré-definida no menu. Não precisas de escrever nem memorizar.</div><button class="blue" onclick="setMode('REAL')">ATIVAR REAL PROTEGIDO</button></div>
<div class="card"><div class="muted">ESTADO</div><div id="status" class="big">---</div><div id="mode" class="muted">---</div></div><div class="card"><div class="muted">SALDO / EQUITY</div><div id="balance" class="big">---</div></div><div class="card"><div class="muted">P&L</div><div id="pnl" class="big">---</div></div><div class="card"><div class="muted">WATCHDOG</div><pre id="watchdog">---</pre></div><div class="card"><div class="muted">CHAMPION / CHALLENGER</div><pre id="champion">---</pre></div>
<div class="card wide"><div class="muted">ATIVOS</div><table><thead><tr><th>Ativo</th><th>Score</th><th>Regime</th></tr></thead><tbody id="assets"></tbody></table></div><div class="card wide"><div class="muted">POSIÇÕES</div><pre id="positions">---</pre></div><div class="card wide"><div class="muted">LOGS</div><pre id="logs">---</pre></div></div>
<script>
const H=()=>({'X-Token':document.getElementById('token').value,'Content-Type':'application/json'});async function api(p,o={}){let r=await fetch(p,{...o,headers:{...H(),...(o.headers||{})}}),d={};try{d=await r.json()}catch(e){}if(!r.ok)throw Error(d.error||d.reason||'Operação recusada');return d}async function cmd(p){try{await api(p,{method:'POST'});refresh()}catch(e){alert(e.message)}}async function arm(){try{await api('/real/arm',{method:'POST',body:JSON.stringify({phrase:document.getElementById('phrase').value})});refresh()}catch(e){alert(e.message)}}async function setMode(m){try{await api('/mode',{method:'POST',body:JSON.stringify({mode:m})});refresh()}catch(e){alert(e.message)}}async function refresh(){try{let d=await api('/status');status.textContent=d.status||'---';mode.textContent='Modo: '+(d.mode||'---');balance.textContent=(d.balance||0).toFixed(2)+' / '+(d.equity||0).toFixed(2);pnl.textContent='Hoje '+((d.pnl_today_pct||0)*100).toFixed(2)+'% | Semana '+((d.pnl_week_pct||0)*100).toFixed(2)+'% | DD '+((d.drawdown_pct||0)*100).toFixed(2)+'%';watchdog.textContent=JSON.stringify(d.watchdog||{},null,2);champion.textContent=JSON.stringify(d.champion_challenger||{},null,2);let s=d.asset_scores||{},r=d.regimes||{};assets.innerHTML=Object.keys(s).map(k=>'<tr><td>'+k+'</td><td>'+Number(s[k]).toFixed(2)+'</td><td>'+(r[k]||'')+'</td></tr>').join('');positions.textContent=JSON.stringify(d.open_positions||{},null,2);logs.textContent=(d.logs||[]).slice(-30).join('\n');let q=await api('/readiness'),e=q.evidence||{};rt.textContent=q.ready?'PRONTO PARA REVISÃO REAL':'REAL BLOQUEADO';rt.className='big '+(q.ready?'ok':'bad');rs.textContent='Market State '+(e.market_state_rows||0)+'/'+(e.required_market_state_rows||0)+' | Outcomes '+(e.outcome_samples||0)+'/'+(e.required_outcome_samples||0)+' | Elegíveis '+(e.eligible_outcomes||0);checks.innerHTML=(q.checks||[]).map(c=>'<div class="check"><span>'+c.name+'</span><span class="'+(c.ok?'ok':'bad')+'">'+(c.ok?'✓ OK':'✕ BLOQUEADO')+'</span></div>').join('');guard.textContent=d.real_mode_guard&&d.real_mode_guard.armed?'Autorizado — '+d.real_mode_guard.remaining_seconds+'s restantes':'REAL sem autorização — bloqueado'}catch(e){status.textContent='OFFLINE / TOKEN'}}setInterval(refresh,4000);refresh();
</script></body></html>'''
