from __future__ import annotations

COCKPIT_HTML = r'''<!doctype html>
<html lang="pt-PT">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Vazao Sovereign Trader</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#08101f;color:#eef4ff;font:15px system-ui,Arial,sans-serif}.top{position:sticky;top:0;padding:14px 16px;background:#0d1629;border-bottom:1px solid #243553;z-index:2}.title{font-size:20px;font-weight:800}.muted{color:#9fb0ca;font-size:13px}.wrap{max-width:1100px;margin:auto;padding:12px;display:grid;gap:12px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:#101a2f;border:1px solid #243553;border-radius:16px;padding:15px}.wide{grid-column:1/-1}.label{color:#9fb0ca;font-size:12px;text-transform:uppercase;font-weight:700;letter-spacing:.08em}.big{font-size:26px;font-weight:850;margin-top:5px}.row{display:flex;flex-wrap:wrap;gap:7px;margin-top:8px}button,input{font:inherit;border-radius:11px;padding:12px;border:1px solid #334968}button{cursor:pointer;font-weight:800;border:0;flex:1 1 130px}.go{background:#37d39a}.pause{background:#f6c453}.stop{background:#ff7187}.blue{background:#9ac7ff}input{width:100%;background:#09111f;color:#eef4ff}.ok{color:#37d39a}.bad{color:#ff7187}.notice{background:#0b1425;padding:11px;border-radius:12px;margin-top:8px}table{width:100%;border-collapse:collapse}td,th{padding:8px;text-align:left;border-bottom:1px solid #243553}pre{white-space:pre-wrap;max-height:220px;overflow:auto}details{margin-top:10px}summary{cursor:pointer;font-weight:800}@media(max-width:700px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:450px){.grid{grid-template-columns:1fr}.card{padding:13px}button{width:100%}}
</style>
</head>
<body>
<header class="top"><div class="title">Vazao Sovereign Trader</div><div class="muted">Painel simples · PAPER por defeito</div></header>
<main class="wrap">
<section class="card wide"><div class="label">Estado</div><div id="status" class="big">A ligar…</div><div id="mode" class="muted">---</div><div id="health" class="notice">A verificar…</div></section>
<section class="card wide"><div class="label">Controlo</div><div class="row"><button class="go" onclick="cmd('/start')">▶ LIGAR</button><button class="pause" onclick="cmd('/pause')">Ⅱ PAUSAR</button><button class="go" onclick="cmd('/resume')">▶ RETOMAR</button><button class="stop" onclick="cmd('/stop')">■ PARAR</button></div><details><summary>Mais opções</summary><div class="row"><button class="blue" onclick="cmd('/preflight')">✓ VERIFICAR</button><button class="blue" onclick="setMode('PAPER')">PAPER</button><button class="blue" onclick="runValidation()">↻ VALIDAR PAPER</button></div><div id="validation" class="muted"></div></details></section>
<section class="grid"><div class="card"><div class="label">Saldo</div><div id="balance" class="big">---</div></div><div class="card"><div class="label">Hoje</div><div id="pnl" class="big">---</div></div><div class="card"><div class="label">Drawdown</div><div id="dd" class="big">---</div></div><div class="card"><div class="label">Watchdog</div><div id="wd" class="big">---</div></div></section>
<section class="card wide"><div class="label">REAL protegido</div><div id="real" class="big">A verificar…</div><div id="realinfo" class="muted"></div><div class="notice">O botão REAL só funciona quando todas as verificações necessárias estiverem OK.</div><div class="row"><button class="blue" onclick="arm()">🔐 AUTORIZAR REAL</button><button class="stop" onclick="cmd('/real/disarm')">🔒 BLOQUEAR REAL</button><button class="blue" onclick="setMode('REAL')">ATIVAR REAL</button></div><details><summary>Ver verificações</summary><div id="checks"></div></details></section>
<section class="card wide"><div class="label">Ajuda no PC / telemóvel</div><div id="bridge">A verificar…</div><div class="muted">Quando for necessária uma intervenção no navegador, ela aparece aqui para ser resolvida no dispositivo que estiveres a usar.</div></section>
<section class="card wide"><div class="label">Ativos</div><table><thead><tr><th>Ativo</th><th>Score</th><th>Regime</th></tr></thead><tbody id="assets"></tbody></table></section>
<section class="grid"><div class="card"><div class="label">Posições</div><pre id="positions">---</pre></div><div class="card"><div class="label">Modelos</div><pre id="models">---</pre></div><div class="card"><div class="label">Eventos</div><pre id="logs">---</pre></div><div class="card"><div class="label">Preflight</div><pre id="preflight">---</pre></div></section>
<section class="card wide"><details><summary>Acesso local</summary><input id="token" type="password" placeholder="Token local, se configurado"><div class="muted">Deixa vazio se não tiveres configurado um token.</div></details></section>
</main>
<script>
const $=id=>document.getElementById(id);const H=()=>({'X-Token':$('token').value,'Content-Type':'application/json'});
async function api(p,o={}){const r=await fetch(p,{...o,headers:{...H(),...(o.headers||{})}});let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw Error(d.error||d.reason||'Operação recusada');return d}
async function cmd(p){try{await api(p,{method:'POST'});refresh()}catch(e){alert(e.message)}}
async function arm(){try{await api('/real/arm',{method:'POST',body:JSON.stringify({phrase:'EU ACEITO O RISCO'})});refresh()}catch(e){alert(e.message)}}
async function setMode(m){try{await api('/mode',{method:'POST',body:JSON.stringify({mode:m})});refresh()}catch(e){alert(e.message)}}
async function runValidation(){try{$('validation').textContent='A validar…';await api('/readiness/run',{method:'POST'});$('validation').textContent='Validação concluída.';refresh()}catch(e){$('validation').textContent='Bloqueada: '+e.message}}
async function refresh(){try{const d=await api('/status');$('status').textContent=d.status||'---';$('mode').textContent='Modo: '+(d.mode||'---');$('health').textContent=d.status==='RUNNING'?'● O BOT ESTÁ A FUNCIONAR':d.status==='PAUSED'?'Ⅱ O BOT ESTÁ PAUSADO':d.status==='SAFE_MODE'?'⚠ MODO SEGURO':'● '+(d.status||'PARADO');$('balance').textContent=(d.balance||0).toFixed(2);$('pnl').textContent=((d.pnl_today_pct||0)*100).toFixed(2)+'%';$('dd').textContent=((d.drawdown_pct||0)*100).toFixed(2)+'%';const w=d.watchdog||{};$('wd').textContent=w.ok===true?'OK':w.ok===false?'ATENÇÃO':'—';$('positions').textContent=JSON.stringify(d.open_positions||{},null,2);$('models').textContent=JSON.stringify(d.champion_challenger||{},null,2);$('preflight').textContent=JSON.stringify(d.preflight||{},null,2);$('logs').textContent=(d.logs||[]).slice(-20).join('\n');const s=d.asset_scores||{},r=d.regimes||{};$('assets').innerHTML=Object.keys(s).map(k=>'<tr><td>'+k+'</td><td>'+Number(s[k]).toFixed(2)+'</td><td>'+(r[k]||'')+'</td></tr>').join('');const q=await api('/readiness'),e=q.evidence||{};$('real').textContent=q.ready?'PRONTO PARA REVISÃO REAL':'REAL BLOQUEADO';$('real').className='big '+(q.ready?'ok':'bad');$('realinfo').textContent='Dados '+(e.market_state_rows||0)+'/'+(e.required_market_state_rows||0)+' · Outcomes '+(e.outcome_samples||0)+'/'+(e.required_outcome_samples||0)+' · Elegíveis '+(e.eligible_outcomes||0);$('checks').innerHTML=(q.checks||[]).map(c=>'<div style="padding:7px 0;border-bottom:1px solid #243553">'+c.name+' — <span class="'+(c.passed?'ok':'bad')+'">'+(c.passed?'OK':'BLOQUEADO')+'</span></div>').join('')}catch(e){$('status').textContent='OFFLINE / token necessário';$('health').textContent='O painel não conseguiu falar com o motor.'}}
async function refreshBridge(){try{const d=await api('/human-interaction/pending');const items=(d.requests||[]).filter(x=>x.status==='PENDING');if(!items.length){$('bridge').innerHTML='<span class="ok">✓ Nada pendente</span>';return}$('bridge').innerHTML=items.map(x=>'<div class="notice"><b>'+x.title+'</b><div class="muted">'+x.platform+' · '+x.kind+'</div><div>'+x.message+'</div><button class="go" onclick="respond(\''+x.request_id+'\')">ENVIAR</button><button class="stop" onclick="cancel(\''+x.request_id+'\')">CANCELAR</button></div>').join('')}catch(e){$('bridge').textContent='Ajuda remota indisponível'}}
async function respond(id){try{await api('/human-interaction/respond',{method:'POST',body:JSON.stringify({request_id:id,action:'fill',values:{}})});refreshBridge()}catch(e){alert(e.message)}}
async function cancel(id){try{await api('/human-interaction/cancel',{method:'POST',body:JSON.stringify({request_id:id})});refreshBridge()}catch(e){alert(e.message)}}
setInterval(refresh,4000);setInterval(refreshBridge,3000);refresh();refreshBridge();
</script></body></html>'''
